### PR TITLE
customer_application

### PR DESCRIPTION
**Pull request by sweta2**

### CODE REVIEW

**Comment by sweta2** [comment]
I have done the task. Please verify it.

**Comment by preety123** [comment]
Well done

**Comment by sweta2** [comment]
Thank you. Please let me know if there is anything else I should look into.

**Comment by sweta2** [comment]
Hi Sweta,

Thanks for writing - we received your project. You don't need to do
anything at this moment.  Our tech evaluator estimates that he'll have
answers for everyone who submitted projects.

Thank you so much!

The Yleana Leadership Academy Hiring Team

**Pull request merged**
